
export const BOOKING_STRINGS = {
  CONFIRMATION: {
    TITLE: "Booking Confirmed!",
    SUBTITLE: "Your booking has been successfully processed. A confirmation has been sent to your email and WhatsApp.",
    BOOKING_ID: "Booking ID",
    PAYMENT_STATUS: "Payment Status",
    PAID: "Paid",
    CAR: "Car",
    PAYMENT_AMOUNT: "Payment Amount",
    DATES: "Dates",
    PICKUP_LOCATION: "Pickup Location",
    NEED_ASSISTANCE: "Need assistance? Contact our support team at:",
    SUPPORT_PHONE: "+91-7066569090",
  },
  SUMMARY: {
    REVIEW_TITLE: "Review Your Booking",
    REVIEW_SUBTITLE: "Please review your booking details before proceeding to payment",
    CAR_DETAILS: "Car Details",
    DAILY_RATE: "Daily Rate",
    EXTRA_KM_RATE: "Extra KM Rate",
    TRIP_DETAILS: "Trip Details",
    START_DATE: "Start Date",
    END_DATE: "End Date",
    DURATION: "Duration",
    DAYS: "days",
    PICKUP_LOCATION: "Pickup Location",
    CONTACT_INFORMATION: "Contact Information",
    FULL_NAME: "Full Name",
    EMAIL: "Email",
    PHONE: "Phone",
    PAYMENT_SUMMARY: "Payment Summary",
    RENTAL: "Rental",
    TOTAL_AMOUNT: "Total Amount",
    EXTRA_KM_CHARGES: "Extra KM charges",
    TOKEN_AMOUNT: "Token Amount",
    REMAINING_AMOUNT: "* Remaining amount to be paid at pickup",
  },
  BUTTONS: {
    BACK: "Back",
    PROCEED_TO_PAYMENT: "Proceed to Payment",
    GO_HOME: "Go Home",
    VIEW_MY_BOOKINGS: "View My Bookings",
    SIGN_IN_TO_CONTINUE: "Sign In to Continue",
    BOOK_A_CAR: "Book a Car",
    BOOK_A_CAR_NOW: "Book a Car Now",
  },
  LOGIN_PROMPT: {
    TITLE: "Login Required",
    MESSAGE: "Please sign in to continue with your booking. Your booking information will be saved to your account.",
  },
  HISTORY: {
    TITLE: "My Bookings",
    NO_ACTIVE_BOOKINGS: "No active bookings",
    NO_ACTIVE_DESCRIPTION: "You don't have any upcoming trips. Book a car to get started!",
    NO_PAST_BOOKINGS: "You don't have any past bookings.",
    PLEASE_LOGIN: "Please log in to view your bookings",
  },
};
